#!/usr/bin/env npx tsx
/**
 * Documentation Gardener
 *
 * Scans the docs/ directory for:
 * - Stale documents (not updated in >90 days)
 * - Broken internal links
 * - Missing index entries
 * - Empty placeholder sections
 *
 * Outputs a report and optionally creates a fix plan.
 */

import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'fs';
import { join, relative, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const DOCS_DIR = resolve(__dirname, '../../../docs');
const STALE_THRESHOLD_DAYS = 90;
const ONE_DAY_MS = 86_400_000;

interface DocIssue {
  file: string;
  type: 'stale' | 'broken-link' | 'empty-section' | 'missing-index';
  message: string;
}

function walkDocs(dir: string, visitor: (fullPath: string) => void): void {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      walkDocs(fullPath, visitor);
    } else if (entry.endsWith('.md')) {
      visitor(fullPath);
    }
  }
}

function checkStaleness(filePath: string): DocIssue | null {
  const stat = statSync(filePath);
  const ageDays = (Date.now() - stat.mtimeMs) / ONE_DAY_MS;
  if (ageDays > STALE_THRESHOLD_DAYS) {
    return {
      file: relative(DOCS_DIR, filePath),
      type: 'stale',
      message: `Document not updated in ${Math.floor(ageDays)} days (threshold: ${STALE_THRESHOLD_DAYS}).`,
    };
  }
  return null;
}

function checkEmptySections(filePath: string): DocIssue[] {
  const issues: DocIssue[] = [];
  const content = readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? '';
    const headingMatch = line.match(/^#+\s+(.+)$/);
    if (headingMatch) {
      // Check if next non-empty line is another heading or end of file
      let j = i + 1;
      while (j < lines.length && (lines[j]?.trim() ?? '') === '') j++;
      const nextLine = lines[j]?.trim() ?? '';
      if (nextLine.startsWith('#') || nextLine === '') {
        if (i < lines.length - 1) {
          issues.push({
            file: relative(DOCS_DIR, filePath),
            type: 'empty-section',
            message: `Section "${headingMatch[1]}" appears to be empty.`,
          });
        }
      }
    }
  }
  return issues;
}

function checkBrokenLinks(filePath: string, allFiles: Set<string>): DocIssue[] {
  const issues: DocIssue[] = [];
  const content = readFileSync(filePath, 'utf-8');
  const linkPattern = /\[([^\]]*)\]\(([^)]+)\)/g;
  let match;

  while ((match = linkPattern.exec(content)) !== null) {
    const linkTarget = match[2]!;
    // Only check relative links (not URLs)
    if (linkTarget.startsWith('http') || linkTarget.startsWith('#')) continue;

    const resolvedPath = join(filePath, '..', linkTarget).replace(/#.*$/, '');
    if (!allFiles.has(resolvedPath)) {
      issues.push({
        file: relative(DOCS_DIR, filePath),
        type: 'broken-link',
        message: `Broken link: [${match[1]}](${linkTarget})`,
      });
    }
  }
  return issues;
}

function main(): void {
  const issues: DocIssue[] = [];

  // Collect all doc files for link checking
  const allFiles = new Set<string>();
  walkDocs(DOCS_DIR, (fp) => allFiles.add(fp));

  // Run checks
  walkDocs(DOCS_DIR, (filePath) => {
    const staleIssue = checkStaleness(filePath);
    if (staleIssue) issues.push(staleIssue);

    issues.push(...checkEmptySections(filePath));
    issues.push(...checkBrokenLinks(filePath, allFiles));
  });

  // Report
  if (issues.length === 0) {
    console.error('[doc-gardener] All documentation is healthy.');
    return;
  }

  console.error(`[doc-gardener] Found ${issues.length} issue(s):\n`);

  const grouped = new Map<string, DocIssue[]>();
  for (const issue of issues) {
    const existing = grouped.get(issue.type) ?? [];
    existing.push(issue);
    grouped.set(issue.type, existing);
  }

  for (const [type, items] of grouped) {
    console.error(`  ${type.toUpperCase()} (${items.length}):`);
    for (const item of items) {
      console.error(`    - ${item.file}: ${item.message}`);
    }
    console.error();
  }

  // Generate fix plan if issues found
  const planDir = join(DOCS_DIR, 'exec-plans/active');
  mkdirSync(planDir, { recursive: true });
  const today = new Date().toISOString().split('T')[0];
  const planPath = join(planDir, `${today}-doc-gardener-fixes.md`);

  const planContent = `# Documentation Garden Fixes

**Created:** ${today}
**Status:** Active
**Priority:** Low
**Generated by:** doc-gardener

## Issues

${issues.map((i) => `- [ ] [${i.type}] ${i.file}: ${i.message}`).join('\n')}

## Steps

${issues.map((i) => `1. [ ] Fix ${i.type} in ${i.file}`).join('\n')}
`;

  writeFileSync(planPath, planContent);
  console.error(`Fix plan generated: ${planPath}`);
}

main();
