// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/"
type AppRouteHandlerRoutes = "/api/agent" | "/api/agent/answer" | "/api/chat" | "/api/config" | "/api/files" | "/api/files/changes" | "/api/files/content" | "/api/files/diff" | "/api/files/search" | "/api/filesystem" | "/api/groups" | "/api/groups/[id]" | "/api/mcp/config" | "/api/mcp/test" | "/api/projects" | "/api/projects/[id]" | "/api/sessions" | "/api/sessions/[id]" | "/api/skills" | "/api/skills/[name]" | "/api/skills/[name]/content" | "/api/skills/[name]/open" | "/api/skills/create" | "/api/skills/search" | "/api/skills/toggle" | "/api/threads" | "/api/threads/[id]" | "/api/threads/[id]/changes" | "/api/tools" | "/api/tools/mcp/search"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/agent": {}
  "/api/agent/answer": {}
  "/api/chat": {}
  "/api/config": {}
  "/api/files": {}
  "/api/files/changes": {}
  "/api/files/content": {}
  "/api/files/diff": {}
  "/api/files/search": {}
  "/api/filesystem": {}
  "/api/groups": {}
  "/api/groups/[id]": { "id": string; }
  "/api/mcp/config": {}
  "/api/mcp/test": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/sessions": {}
  "/api/sessions/[id]": { "id": string; }
  "/api/skills": {}
  "/api/skills/[name]": { "name": string; }
  "/api/skills/[name]/content": { "name": string; }
  "/api/skills/[name]/open": { "name": string; }
  "/api/skills/create": {}
  "/api/skills/search": {}
  "/api/skills/toggle": {}
  "/api/threads": {}
  "/api/threads/[id]": { "id": string; }
  "/api/threads/[id]/changes": { "id": string; }
  "/api/tools": {}
  "/api/tools/mcp/search": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
